services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: django-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - server/employeemanagement/.local_env
    depends_on:
      - db
    command: python server/employeemanagement/manage.py runserver 0.0.0.0:8000

  db:
    image: mysql:8.0
    container_name: mysql-db
    # restart: always
    env_file:
      - server/employeemanagement/.local_env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: